// Batch two skeleton: clusters (with series tag), cross-cluster map, batch-one link targets, per-post core fields.
// Post tuple: [slug, title, author, audience, intent, primaryKeyword, handles[], query, heading]
const H = "hariharan", A = "archana", M = "manikandan";
const G = "general", N = "nri-us", S = "seeker";
const KALA = "rahu-ketu-dosha-parihara-pooja-sarpa-dosha-parihara-pooja-at-sri-kalahasti-temple";
const SHAKTI = "shakti-samriddhi-pooja-for-feminine-prosperity-family-well-being";
const ANNA = "annadhanam-donate-food-to-homeless-children";
const KAVACH = "ganesha-hanuman-shakti-kavach-the-shield-of-protection-and-victory";
const DURGA = "mantra-chanting-of-700-verses-of-durga-saptashati";
const SHANI = "saturn-transit-shani-peyarchi";

export const clusters = [
  // ---------------- SERIES: nakshatra (27) ----------------
  { id: "birth-stars", name: "Birth stars (nakshatras)", series: "nakshatra", audience: G, seasonality: "year-round; each star recurs monthly (star birthday)", primaryKeyword: "nakshatra meaning", cross: ["rasis", "astrology-practice", "navagraha-grahas"], b1: ["ayushya-homam-star-birthday", "what-is-sankalpam", "vedic-vs-western-astrology"], posts: [
    ["ashwini-nakshatra", "Ashwini Nakshatra: The Healers' Star and Its Temple", H, G, "informational", "ashwini nakshatra", ["dhanwantari-homam"], "", "Poojas for Ashwini"],
    ["bharani-nakshatra", "Bharani Nakshatra: Yama's Star, Restraint and Renewal", A, G, "informational", "bharani nakshatra", [], "Durga", ""],
    ["krittika-nakshatra", "Krittika Nakshatra (Karthigai): The Star of Fire", M, G, "informational", "krittika nakshatra", ["palani"], "", ""],
    ["rohini-nakshatra", "Rohini Nakshatra: Krishna's Birth Star, Explained", H, G, "informational", "rohini nakshatra", [], "Krishna", ""],
    ["mrigashira-nakshatra", "Mrigashira Nakshatra: The Seeker's Star and Its Ways", A, G, "informational", "mrigashira nakshatra", [], "Murugan", ""],
    ["ardra-nakshatra", "Ardra Nakshatra (Thiruvathirai): Storm, Tears, Shiva", M, G, "informational", "ardra nakshatra", ["maha-shivaratri"], "", ""],
    ["punarvasu-nakshatra", "Punarvasu Nakshatra: Rama's Star of Return", H, G, "informational", "punarvasu nakshatra", ["guru-jupiter-transit"], "", ""],
    ["pushya-nakshatra", "Pushya Nakshatra (Poosam): The Nourishing Star", A, G, "informational", "pushya nakshatra", ["guru-jupiter-transit"], "", ""],
    ["ashlesha-nakshatra", "Ashlesha Nakshatra (Ayilyam): The Serpent's Star", M, G, "informational", "ashlesha nakshatra", [KALA], "", ""],
    ["magha-nakshatra", "Magha Nakshatra (Magam): The Ancestors' Throne", H, G, "informational", "magha nakshatra", ["tila-homam-at-rameswaram"], "", ""],
    ["purva-phalguni-nakshatra", "Purva Phalguni (Pooram) Nakshatra: Rest and Delight", A, G, "informational", "purva phalguni nakshatra", ["swayamvara-parvathi-homam"], "", ""],
    ["uttara-phalguni-nakshatra", "Uttara Phalguni (Uthiram): The Star of Promises", M, G, "informational", "uttara phalguni nakshatra", ["swayamvara-parvathi-homam"], "", ""],
    ["hasta-nakshatra", "Hasta Nakshatra (Hastham): The Star of Skilled Hands", H, G, "informational", "hasta nakshatra", [], "Surya", ""],
    ["chitra-nakshatra", "Chitra Nakshatra (Chithirai): The Builder's Bright Star", A, G, "informational", "chitra nakshatra", [], "Navagraha", ""],
    ["swati-nakshatra", "Swati Nakshatra (Swathi): The Wind's Independent Star", M, G, "informational", "swati nakshatra", ["sudarsana-homam"], "", ""],
    ["vishakha-nakshatra", "Vishakha Nakshatra (Visakam): Murugan's Forked Star", H, G, "informational", "vishakha nakshatra", ["palani"], "", ""],
    ["anuradha-nakshatra", "Anuradha Nakshatra (Anusham): Friendship and Devotion", A, G, "informational", "anuradha nakshatra", [SHANI], "", ""],
    ["jyeshtha-nakshatra", "Jyeshtha Nakshatra (Kettai): The Eldest's Burden", M, G, "informational", "jyeshtha nakshatra", [], "Hanuman", ""],
    ["mula-nakshatra", "Mula Nakshatra (Moolam): The Root Star, Without Fear", H, G, "informational", "mula nakshatra", [KAVACH], "", ""],
    ["purva-ashadha-nakshatra", "Purva Ashadha (Pooradam) Nakshatra: The Waters' Star", A, G, "informational", "purva ashadha nakshatra", [], "Varuna", ""],
    ["uttara-ashadha-nakshatra", "Uttara Ashadha (Uthiradam): The Star of Final Victory", M, G, "informational", "uttara ashadha nakshatra", ["maha-ganapathy-homam"], "", ""],
    ["shravana-nakshatra", "Shravana Nakshatra (Thiruvonam): The Listener's Star", H, G, "informational", "shravana nakshatra", [], "Vishnu", ""],
    ["dhanishta-nakshatra", "Dhanishta Nakshatra (Avittam): Rhythm and Wealth", A, G, "informational", "dhanishta nakshatra", [], "Murugan", ""],
    ["shatabhisha-nakshatra", "Shatabhisha Nakshatra (Sadayam): A Hundred Healers", M, G, "informational", "shatabhisha nakshatra", ["dhanwantari-homam"], "", ""],
    ["purva-bhadrapada-nakshatra", "Purva Bhadrapada (Poorattathi): The Star of Intensity", H, G, "informational", "purva bhadrapada nakshatra", ["guru-jupiter-transit"], "", ""],
    ["uttara-bhadrapada-nakshatra", "Uttara Bhadrapada (Uthirattathi): Deep Water, Calm", A, G, "informational", "uttara bhadrapada nakshatra", [SHANI], "", ""],
    ["revati-nakshatra", "Revati Nakshatra: The Last Star and Safe Journeys", M, G, "informational", "revati nakshatra", [], "Vishnu", ""],
  ]},
  // ---------------- SERIES: rasi (12) ----------------
  { id: "rasis", name: "The twelve rasis (moon signs)", series: "rasi", audience: G, seasonality: "year-round; peaks at transits (peyarchi)", primaryKeyword: "rasi meaning", cross: ["birth-stars", "navagraha-grahas", "astrology-practice"], b1: ["guru-peyarchi-jupiter-transit", "shani-sade-sati-explained", "reading-your-birth-chart-calmly"], posts: [
    ["mesha-rasi", "Mesha Rasi (Aries): Mars, Courage and Its Temples", H, G, "informational", "mesha rasi", ["navagraha-homam"], "", ""],
    ["rishabha-rasi", "Rishabha Rasi (Taurus): Venus, Steadiness, Worship", A, G, "informational", "rishabha rasi", [], "Lakshmi", ""],
    ["mithuna-rasi", "Mithuna Rasi (Gemini): Mercury and the Restless Mind", M, G, "informational", "mithuna rasi", ["hayagreeva-homam"], "", ""],
    ["kataka-rasi", "Kataka Rasi (Cancer): The Moon's Sign and Its Poojas", H, G, "informational", "kataka rasi", [], "Parvati", ""],
    ["simha-rasi", "Simha Rasi (Leo): The Sun's Sign, Pride and Service", A, G, "informational", "simha rasi", ["navagraha-homam"], "", ""],
    ["kanya-rasi", "Kanya Rasi (Virgo): Mercury, Detail and Devotion", M, G, "informational", "kanya rasi", ["saraswati-homam"], "", ""],
    ["tula-rasi", "Tula Rasi (Libra): Venus and the Art of Balance", H, G, "informational", "tula rasi", [], "Lakshmi", ""],
    ["vrischika-rasi", "Vrischika Rasi (Scorpio): Depth, Mars and Murugan", A, G, "informational", "vrischika rasi", ["palani"], "", ""],
    ["dhanu-rasi", "Dhanu Rasi (Sagittarius): Jupiter's Archer", M, G, "informational", "dhanu rasi", ["guru-jupiter-transit"], "", ""],
    ["makara-rasi", "Makara Rasi (Capricorn): Saturn, Work and Patience", H, G, "informational", "makara rasi", [SHANI], "", ""],
    ["kumbha-rasi", "Kumbha Rasi (Aquarius): Saturn's Water-Bearer", A, G, "informational", "kumbha rasi", [SHANI], "", ""],
    ["meena-rasi", "Meena Rasi (Pisces): Jupiter, Compassion, Letting Go", M, G, "informational", "meena rasi", ["guru-jupiter-transit"], "", ""],
  ]},
  // ---------------- SERIES: recipes (20) ----------------
  { id: "naivedyam-recipes", name: "Naivedyam recipes for everyday pooja", series: "recipes", audience: G, seasonality: "year-round; Fridays, full moons, monthly vratams", primaryKeyword: "naivedyam recipes", cross: ["festival-prasadam", "weekday-vratams", "food-and-body"], b1: ["prasad-and-gratitude", "why-prasadam-is-shared", "puja-at-home-step-by-step"], posts: [
    ["sakkarai-pongal-for-pooja", "Sakkarai Pongal for Pooja: Jaggery, Ghee, Patience", A, G, "how-to", "sakkarai pongal recipe", [], "Lakshmi", ""],
    ["ven-pongal-temple-style", "Ven Pongal, Temple Style: Pepper, Cumin and Ghee", A, N, "how-to", "ven pongal recipe", [], "Vishnu", ""],
    ["paal-payasam-naivedyam", "Paal Payasam for Naivedyam: Slow Milk, Simple Rice", A, G, "how-to", "paal payasam recipe", [], "Lakshmi", ""],
    ["panchamrutham-at-home", "Panchamrutham at Home: The Five Nectars for Abhishekam", A, G, "how-to", "panchamrutham recipe", ["palani-panchamritham"], "", ""],
    ["sundal-for-navratri-and-fridays", "Sundal Recipe for Pooja: Chickpeas, Coconut, Care", M, N, "how-to", "sundal recipe for pooja", [], "Durga", ""],
    ["puliyodarai-temple-tamarind-rice", "Puliyodarai: The Temple Tamarind Rice at Home", M, G, "how-to", "puliyodarai recipe", [], "Vishnu", ""],
    ["daddojanam-curd-rice-prasadam", "Daddojanam: Curd Rice as Prasadam, Cool and Kind", A, G, "how-to", "daddojanam recipe", [], "Vishnu", ""],
    ["rava-kesari-naivedyam", "Rava Kesari for Naivedyam in Twenty Minutes", A, N, "how-to", "rava kesari naivedyam", [], "Ganesha", ""],
    ["nei-appam-for-pooja", "Nei Appam for Pooja: Rice, Jaggery, Banana", H, G, "how-to", "nei appam recipe", [], "Ganesha", ""],
    ["vadai-mala-for-hanuman", "Vadai Mala for Hanuman: Why Vadas, How to Make", H, G, "how-to", "vadai mala for hanuman", [KAVACH], "", ""],
  ]},
  { id: "festival-prasadam", name: "Festival prasadam recipes", series: "recipes", audience: G, seasonality: "festival-linked through the year", primaryKeyword: "festival prasadam recipes", cross: ["naivedyam-recipes", "festivals-krishna-ganesha", "festivals-new-year"], b1: ["why-is-pongal-celebrated", "sankatahara-chaturthi-fast", "prasad-and-gratitude"], posts: [
    ["modak-for-ganesh-chaturthi", "Modak for Ganesh Chaturthi: Steamed Kozhukattai", A, N, "how-to", "modak recipe for ganesh chaturthi", ["maha-ganapathy-homam"], "", ""],
    ["panakam-and-neer-mor", "Panakam and Neer Mor: Ram Navami's Cooling Drinks", A, G, "how-to", "panakam recipe", [], "Rama", ""],
    ["aval-for-krishna-janmashtami", "Aval for Krishna: Sweet Poha and Sudama's Gift", H, G, "how-to", "aval recipe for krishna jayanthi", [], "Krishna", ""],
    ["seedai-for-gokulashtami", "Seedai for Gokulashtami: Small Crunchy Offerings", A, N, "how-to", "seedai recipe", [], "Krishna", ""],
    ["ugadi-pachadi-six-tastes", "Ugadi Pachadi: Six Tastes in One Spoon", A, G, "how-to", "ugadi pachadi recipe", [], "Ganesha", ""],
    ["ada-pradhaman-for-onam", "Ada Pradhaman for Onam: The Payasam of Kerala", A, N, "how-to", "ada pradhaman recipe", [ANNA], "", ""],
    ["thiruvathirai-kali-recipe", "Thiruvathirai Kali: The Sweet Offered to Nataraja", M, G, "how-to", "thiruvathirai kali recipe", [], "Shiva", ""],
    ["ellu-urundai-sesame-balls", "Ellu Urundai: Sesame Balls for Saturn and Winter", A, G, "how-to", "ellu urundai recipe", [SHANI], "", ""],
    ["varalakshmi-vratham-naivedyam", "Varalakshmi Vratham Naivedyam: What to Cook", M, N, "how-to", "varalakshmi vratham naivedyam", [SHAKTI], "", ""],
    ["karadaiyan-nombu-adai", "Karadaiyan Nombu Adai: Savitri's Offering", A, G, "how-to", "karadaiyan nombu adai recipe", [SHAKTI], "", ""],
  ]},
  // ---------------- SERIES: temples (15) ----------------
  { id: "our-temples", name: "Temples where our poojas are performed", series: "temples", audience: G, seasonality: "year-round", primaryKeyword: "temple pooja online", cross: ["temples-devotees-ask", "homams-explained-2", "nri-practice"], b1: ["online-puja-from-usa-explained", "joining-a-puja-across-time-zones", "six-abodes-of-murugan"], posts: [
    ["kanchi-kamakshi-temple", "Kanchi Kamakshi Temple: The Goddess of Loving Eyes", H, G, "informational", "kanchi kamakshi temple", ["kanchi-kamakshi"], "", ""],
    ["palani-murugan-temple", "Palani Murugan Temple: The Hill of the Renouncer", M, G, "informational", "palani murugan temple history", ["palani", "palani-panchamritham"], "", ""],
    ["brahma-vidya-ganapati-temple", "Brahma Vidya Ganapati Temple, Bengaluru: A Guide", A, N, "informational", "brahma vidya ganapati temple", ["brahmavidyaganapati"], "", ""],
    ["sri-kalahasti-temple-guide", "Sri Kalahasti Temple: Wind, Spider, Snake, Elephant", H, G, "informational", "sri kalahasti temple", [KALA], "", ""],
    ["thirunallar-saniswaran-temple", "Thirunallar Saniswaran Temple: Nala's Release", M, G, "informational", "thirunallar temple", [SHANI], "", ""],
    ["rameswaram-ramanathaswamy-temple", "Rameswaram Temple: The Lingam Rama Made of Sand", H, G, "informational", "rameswaram temple history", ["tila-homam-at-rameswaram"], "", ""],
    ["shirdi-sai-baba-udi", "Shirdi Sai Baba's Udi: Ash, Faith and Sharing", M, N, "informational", "shirdi sai baba udi", ["shirdi-sai-baba-udi-prasadham"], "", ""],
    ["madurai-meenakshi-temple", "Madurai Meenakshi Temple: A Devotee's Guide", A, G, "informational", "meenakshi temple madurai", [SHAKTI], "", ""],
  ]},
  { id: "temples-devotees-ask", name: "Temples devotees ask about", series: "temples", audience: G, seasonality: "year-round; festival peaks", primaryKeyword: "famous hindu temples south india", cross: ["our-temples", "vishnu-avatars", "shiva-parvati"], b1: ["tiruvannamalai-deepam-from-afar", "vaikunta-ekadashi-significance", "karthigai-deepam-significance"], posts: [
    ["srirangam-temple-guide", "Srirangam Temple: Vishnu Asleep on the River", H, G, "informational", "srirangam temple", [], "Vishnu", ""],
    ["tirupati-balaji-temple-story", "Tirupati Balaji: The Story Behind the Hair and Hundi", M, N, "informational", "tirupati balaji story", [], "Venkateswara", ""],
    ["guruvayur-temple-guide", "Guruvayur Temple: Krishna the Child in Kerala", A, G, "informational", "guruvayur temple", [], "Krishna", ""],
    ["chidambaram-nataraja-temple", "Chidambaram Temple: The Dance and the Empty Space", H, S, "informational", "chidambaram temple", ["maha-shivaratri"], "", ""],
    ["thanjavur-big-temple", "Thanjavur Big Temple: Brihadeeswarar and Its Shadow", M, G, "informational", "thanjavur brihadeeswarar temple", [], "Shiva", ""],
    ["sabarimala-ayyappa-vratham", "Sabarimala and the Ayyappa Vratham: Forty-One Days", A, G, "informational", "sabarimala ayyappa vratham", [], "Ayyappa", ""],
    ["kashi-vishwanath-temple", "Kashi Vishwanath Temple: Why Varanasi Matters", A, S, "informational", "kashi vishwanath temple", ["tila-homam-at-rameswaram"], "", ""],
  ]},
  // ---------------- SERIES: stotras (15) ----------------
  { id: "stotras-explained", name: "Stotras explained", series: "stotras", audience: G, seasonality: "year-round", primaryKeyword: "stotram meaning", cross: ["mantras-explained", "inner-practice", "feminine-shakti"], b1: ["what-is-a-mantra", "chanting-for-beginners", "durga-saptashati-for-beginners"], posts: [
    ["lalitha-sahasranamam-meaning", "Lalitha Sahasranamam Meaning and How to Begin", A, G, "informational", "lalitha sahasranamam meaning", [SHAKTI], "", ""],
    ["vishnu-sahasranamam-for-beginners", "Vishnu Sahasranamam for Beginners: A Gentle Start", M, N, "how-to", "vishnu sahasranamam for beginners", [], "Vishnu", ""],
    ["kanda-sashti-kavasam-meaning", "Kanda Sashti Kavasam Meaning: Murugan's Armour", H, G, "informational", "kanda sashti kavasam meaning", ["palani"], "", ""],
    ["aditya-hrudayam-meaning", "Aditya Hrudayam Meaning: Rama's Prayer to the Sun", H, G, "informational", "aditya hrudayam meaning", ["navagraha-homam"], "", ""],
    ["abhirami-anthathi-meaning", "Abhirami Anthathi: The Poet Who Made the Moon Rise", H, G, "story", "abhirami anthathi meaning", [SHAKTI], "", ""],
    ["soundarya-lahari-explained", "Soundarya Lahari Explained: Beauty as the Goddess", A, S, "informational", "soundarya lahari meaning", [], "Devi", ""],
    ["tiruppavai-meaning", "Tiruppavai Meaning: Andal's Thirty Dawn Songs", M, G, "informational", "tiruppavai meaning", [], "Vishnu", ""],
    ["kolaru-pathigam-navagraha", "Kolaru Pathigam: The Tamil Hymn for the Nine Planets", M, G, "informational", "kolaru pathigam", ["navagraha-homam"], "", ""],
  ]},
  { id: "mantras-explained", name: "Mantras explained", series: "stotras", audience: S, seasonality: "year-round; exam season for Saraswati", primaryKeyword: "mantra meaning", cross: ["stotras-explained", "inner-practice", "homams-explained-2"], b1: ["what-is-a-mantra", "gayatri-mantra-meaning", "simple-mantras-for-kids"], posts: [
    ["saraswati-mantra-for-students", "Saraswati Mantra for Students: Ya Kundendu Explained", A, N, "how-to", "saraswati mantra for students", ["saraswati-homam"], "", ""],
    ["vakratunda-mahakaya-meaning", "Vakratunda Mahakaya Meaning: The First Prayer", H, S, "informational", "vakratunda mahakaya meaning", ["maha-ganapathy-homam"], "", ""],
    ["om-sahana-vavatu-meaning", "Om Sahana Vavatu Meaning: The Teacher-Student Prayer", A, S, "informational", "om sahana vavatu meaning", [], "Saraswati", ""],
    ["mahalakshmi-ashtakam-meaning", "Mahalakshmi Ashtakam Meaning, Verse by Verse", H, G, "informational", "mahalakshmi ashtakam meaning", ["diwali-puja"], "", ""],
    ["dhanvantari-mantra-meaning", "Dhanvantari Mantra: A Prayer for Healing, Explained", A, G, "informational", "dhanvantari mantra", ["dhanwantari-homam"], "", ""],
    ["hare-krishna-maha-mantra", "Hare Krishna Maha Mantra: Meaning and Practice", A, S, "informational", "hare krishna maha mantra meaning", [], "Krishna", ""],
    ["lingashtakam-meaning", "Lingashtakam Meaning: Eight Verses to the Lingam", M, G, "informational", "lingashtakam meaning", ["maha-shivaratri"], "", ""],
  ]},
  // ---------------- SERIES: mythology & ideas (40) ----------------
  { id: "ganesha-stories", name: "Ganesha stories decoded", series: "mythology", audience: G, seasonality: "year-round; peaks at Ganesh Chaturthi", primaryKeyword: "ganesha stories", cross: ["festivals-krishna-ganesha", "vishnu-avatars", "symbols-explained"], b1: ["why-ganesha-comes-first", "sankatahara-chaturthi-fast"], posts: [
    ["ganesha-broken-tusk-story", "Ganesha's Broken Tusk: Why the Scribe Broke His Pen", H, G, "story", "ganesha broken tusk story", ["maha-ganapathy-homam"], "", ""],
    ["ganesha-mouse-vahana-meaning", "Ganesha and the Mouse: What the Vahana Means", H, S, "story", "ganesha mouse meaning", [], "Ganesha", ""],
    ["ganesha-kartikeya-mango-story", "Ganesha, Kartikeya and the Mango: The Loser's Story", H, G, "story", "ganesha and kartikeya mango story", ["palani"], "", ""],
    ["ganesha-elephant-head-story", "Why Ganesha Has an Elephant Head: The Story Decoded", H, G, "story", "why ganesha has an elephant head", ["maha-ganapathy-homam"], "", ""],
  ]},
  { id: "vishnu-avatars", name: "Vishnu and the avatars", series: "mythology", audience: G, seasonality: "year-round", primaryKeyword: "vishnu avatars meaning", cross: ["ganesha-stories", "temples-devotees-ask", "many-paths"], b1: ["vaikunta-ekadashi-significance", "holi-meaning-prahlad-holika", "sudarshana-homam-meaning"], posts: [
    ["dashavatara-meaning", "Dashavatara Meaning: Ten Avatars, One Idea", H, S, "story", "dashavatara meaning", ["sudarsana-homam"], "", ""],
    ["samudra-manthan-meaning", "Samudra Manthan: What the Churning of the Ocean Means", H, G, "story", "samudra manthan meaning", [], "Vishnu", ""],
    ["narasimha-avatar-meaning", "Narasimha Avatar: The In-Between God", H, G, "story", "narasimha avatar story", ["sudarsana-homam"], "", ""],
    ["vamana-three-steps-story", "Vamana's Three Steps: The Dwarf Who Measured Everything", H, G, "story", "vamana avatar story", [], "Vishnu", ""],
    ["rama-maryada-purushottama", "Rama as Maryada Purushottama: The Cost of Being Ideal", H, S, "story", "maryada purushottam meaning", [], "Rama", ""],
    ["krishna-govardhana-story", "Krishna Lifts Govardhana: The Mountain and the Umbrella", H, G, "story", "govardhan story meaning", [], "Krishna", ""],
  ]},
  { id: "shiva-parvati", name: "Shiva and Parvati stories", series: "mythology", audience: G, seasonality: "year-round; peaks at Shivaratri and Pradosham", primaryKeyword: "shiva parvati stories", cross: ["feminine-shakti", "temples-devotees-ask", "stotras-explained"], b1: ["maha-shivaratri-meaning", "pradosham-meaning", "swayamvara-parvathi-story"], posts: [
    ["ardhanarishvara-meaning", "Ardhanarishvara Meaning: Half Shiva, Half Shakti", H, S, "story", "ardhanarishvara meaning", ["maha-shivaratri"], "", ""],
    ["nataraja-symbolism", "Nataraja Symbolism: Reading the Dancing Shiva", H, G, "story", "nataraja symbolism", ["maha-shivaratri"], "", ""],
    ["neelakantha-blue-throat-story", "Neelakantha: Why Shiva Held the Poison in His Throat", H, G, "story", "neelakantha story", ["mrityunjaya-homam"], "", ""],
    ["parvati-tapas-practice", "Parvati's Tapas: What Her Discipline Teaches Us", A, G, "story", "parvati tapas story", ["swayamvara-parvathi-homam"], "", ""],
  ]},
  { id: "feminine-shakti", name: "The feminine and Shakti", series: "mythology", audience: G, seasonality: "year-round; peaks at Navratri and Aadi", primaryKeyword: "women in hinduism", cross: ["shiva-parvati", "tirukkural", "festivals-aadi-monsoon"], b1: ["kanya-puja-meaning", "why-navratri-lasts-nine-nights", "swayamvara-parvathi-story"], posts: [
    ["women-in-hinduism-goddess", "Women in Hinduism: What the Goddess Stories Say", H, S, "informational", "women in hinduism", [SHAKTI], "", ""],
    ["meenakshi-the-queen-who-ruled", "Meenakshi: The Goddess Who Ruled Before She Married", H, G, "story", "meenakshi story", [SHAKTI], "", ""],
    ["andal-story-meaning", "Andal: The Girl Who Wore the Garland First", H, G, "story", "andal story", [], "Vishnu", ""],
    ["avvaiyar-wisdom-sayings", "Avvaiyar's Sayings: The Grandmother Poet of Tamil", M, G, "informational", "avvaiyar sayings", [], "Ganesha", ""],
    ["karaikkal-ammaiyar-story", "Karaikkal Ammaiyar: The Saint Who Chose Her Own Form", M, G, "story", "karaikkal ammaiyar story", [], "Shiva", ""],
    ["shakti-in-daily-practice", "Shakti in Practice: The Feminine as Living Energy", A, S, "informational", "shakti meaning in hinduism", [SHAKTI], "", ""],
  ]},
  { id: "dharma-in-business", name: "Dharma in business and right earning", series: "mythology", audience: G, seasonality: "year-round; peaks at Diwali and Akshaya Tritiya", primaryKeyword: "hinduism business ethics", cross: ["tirukkural", "career-and-work", "many-paths"], b1: ["dharma-meaning-in-everyday-life", "lakshmi-puja-at-home-abroad", "karma-explained-simply"], posts: [
    ["hinduism-business-ethics", "Hinduism and Business Ethics: Dharma at the Counter", M, S, "informational", "hinduism business ethics", ["diwali-puja"], "", ""],
    ["kubera-story-meaning", "Kubera's Story: The God of Wealth Who Was a Treasurer", H, G, "story", "kubera story", ["diwali-puja"], "", ""],
    ["lakshmi-restless-goddess", "Why Lakshmi Is Called Restless: Wealth That Moves", H, G, "story", "why lakshmi is restless", ["diwali-puja"], "", ""],
    ["honest-trade-thathas-shop", "Honesty in Business: Lessons From a Kumbakonam Shop", M, N, "informational", "honesty in business hinduism", [ANNA], "", ""],
  ]},
  { id: "many-paths", name: "Hinduism's many paths", series: "mythology", audience: S, seasonality: "year-round", primaryKeyword: "hinduism many paths", cross: ["seeker-questions", "philosophy-basics", "vishnu-avatars"], b1: ["spiritual-but-not-religious-hinduism", "meditation-vs-puja", "why-do-hindus-do-rituals"], posts: [
    ["ishta-devata-meaning", "Ishta Devata Meaning: Choosing Your Own God", H, S, "informational", "ishta devata meaning", [], "Ganesha", ""],
    ["many-paths-one-truth", "Ekam Sat: Many Paths, One Truth in the Rig Veda", H, S, "informational", "ekam sat vipra bahudha vadanti", [], "Vishnu", ""],
    ["debate-as-devotion-shastrartha", "Shastrartha: Why Hindu Texts Love a Good Debate", H, S, "story", "shastrartha debate hinduism", [], "Saraswati", ""],
    ["householder-and-forest-dweller", "The Four Ashramas: The Household and the Forest", H, S, "informational", "four ashramas of life", [], "Shiva", ""],
  ]},
  { id: "tirukkural", name: "Tirukkural for daily life", series: "mythology", audience: G, seasonality: "year-round; Thiruvalluvar Day in Thai", primaryKeyword: "thirukkural meaning", cross: ["dharma-in-business", "feminine-shakti", "philosophy-basics"], b1: ["dharma-meaning-in-everyday-life", "karma-explained-simply", "annadhanam-feeding-as-worship"], posts: [
    ["who-was-thiruvalluvar", "Who Was Thiruvalluvar? The Poet Behind the Kural", H, G, "informational", "who was thiruvalluvar", [], "Saraswati", ""],
    ["tirukkural-for-daily-life", "Tirukkural for Daily Life: A Beginner's Way In", M, N, "how-to", "thirukkural for daily life", [], "Saraswati", ""],
    ["tirukkural-on-wealth", "Tirukkural on Wealth: Earning Without Losing Yourself", M, G, "informational", "thirukkural on wealth", ["diwali-puja"], "", ""],
    ["tirukkural-on-anger", "Tirukkural on Anger: The Fire That Burns the Holder", M, G, "informational", "thirukkural on anger", [], "Shiva", ""],
    ["tirukkural-on-sweet-speech", "Tirukkural on Kind Words: Why Sweet Speech Matters", M, G, "informational", "thirukkural on speech", [], "Saraswati", ""],
    ["tirukkural-on-gratitude", "Tirukkural on Gratitude: The Help You Cannot Repay", M, N, "informational", "thirukkural on gratitude", [ANNA], "", ""],
    ["tirukkural-on-friendship", "Tirukkural on Friendship: The Hand That Catches the Cloth", M, G, "informational", "thirukkural on friendship", [], "Krishna", ""],
    ["tirukkural-on-learning", "Tirukkural on Learning: Kalvi and the Lifelong Student", H, G, "informational", "thirukkural on education", ["saraswati-homam"], "", ""],
    ["tirukkural-on-patience", "Tirukkural on Patience: Bearing Like the Earth", M, S, "informational", "thirukkural on patience", [], "Bhumi Devi", ""],
    ["tirukkural-on-hospitality", "Tirukkural on Hospitality: The Guest at the Door", M, N, "informational", "thirukkural on hospitality", [ANNA], "", ""],
    ["tirukkural-on-love", "Tirukkural on Love: Anbu as the Breath of Life", A, S, "informational", "thirukkural on love", [], "Shiva", ""],
    ["tirukkural-on-effort", "Tirukkural on Effort: When Fate Says No, Try Again", M, G, "informational", "thirukkural on hard work", ["career-astrology"], "", ""],
  ]},
  // ---------------- SERIES: festivals (25) ----------------
  { id: "festivals-new-year", name: "New year and spring festivals", series: "festivals", audience: G, seasonality: "Mar–Apr (Chaitra / Chithirai)", primaryKeyword: "ugadi significance", cross: ["festivals-summer", "festival-prasadam", "vishnu-avatars"], b1: ["hindu-festival-calendar-usa", "explaining-hindu-festivals-to-coworkers"], posts: [
    ["ugadi-significance", "Ugadi Significance: A New Year That Tastes Bitter Too", H, G, "seasonal", "ugadi significance", [], "Ganesha", ""],
    ["puthandu-tamil-new-year-usa", "Puthandu in the USA: Tamil New Year Far From Home", M, N, "seasonal", "tamil new year puthandu", [], "Ganesha", ""],
    ["vishu-kani-meaning", "Vishu Kani: The First Thing You See in the New Year", M, G, "seasonal", "vishu kani meaning", [], "Krishna", ""],
    ["ram-navami-puja-at-home", "Ram Navami Puja at Home: A Simple Noon Ritual", A, N, "seasonal", "ram navami puja at home", [], "Rama", ""],
    ["hanuman-jayanti-significance", "Hanuman Jayanti Significance: Strength That Serves", H, G, "seasonal", "hanuman jayanti significance", [KAVACH], "", ""],
  ]},
  { id: "festivals-summer", name: "Summer festivals", series: "festivals", audience: G, seasonality: "Apr–Jun (Chithirai, Vaikasi)", primaryKeyword: "akshaya tritiya significance", cross: ["festivals-new-year", "dharma-in-business", "our-temples"], b1: ["hindu-festival-calendar-usa", "six-abodes-of-murugan"], posts: [
    ["akshaya-tritiya-significance", "Akshaya Tritiya Significance: What Never Runs Out", H, G, "seasonal", "akshaya tritiya significance", ["diwali-puja", ANNA], "", ""],
    ["vaikasi-visakam-murugan", "Vaikasi Visakam: Murugan's Birthday, Kept at Home", M, N, "seasonal", "vaikasi visakam", ["palani"], "", ""],
    ["chitra-pournami-meaning", "Chitra Pournami: The Full Moon of the Record-Keeper", A, G, "seasonal", "chitra pournami", [], "Chitragupta", ""],
    ["meenakshi-thirukalyanam-festival", "Meenakshi Thirukalyanam: The Wedding a City Attends", M, G, "seasonal", "meenakshi thirukalyanam", [SHAKTI], "", ""],
  ]},
  { id: "festivals-aadi-monsoon", name: "Aadi and monsoon festivals", series: "festivals", audience: G, seasonality: "Jul–Aug (Aadi, Avani / Shravana)", primaryKeyword: "aadi month significance", cross: ["feminine-shakti", "festival-prasadam", "festivals-krishna-ganesha"], b1: ["lakshmi-puja-at-home-abroad", "amavasya-and-ancestors"], posts: [
    ["aadi-month-significance", "Aadi Month Significance: The Goddess Season", H, G, "seasonal", "aadi month significance", [SHAKTI], "", ""],
    ["aadi-perukku-meaning", "Aadi Perukku: Thanking the River When It Rises", M, G, "seasonal", "aadi perukku", [], "Kaveri", ""],
    ["varalakshmi-vratham-at-home", "Varalakshmi Vratham at Home, Abroad and on a Workday", A, N, "seasonal", "varalakshmi vratham pooja at home", [SHAKTI], "", ""],
    ["avani-avittam-meaning", "Avani Avittam: Changing the Sacred Thread, Renewing Study", M, G, "seasonal", "avani avittam", [], "Hayagriva", ""],
    ["naga-panchami-meaning", "Naga Panchami Meaning: Why Hindus Honour Snakes", H, G, "seasonal", "naga panchami significance", [KALA], "", ""],
  ]},
  { id: "festivals-krishna-ganesha", name: "Janmashtami, Ganesh Chaturthi, Onam", series: "festivals", audience: N, seasonality: "Aug–Sep (Shravana, Bhadrapada)", primaryKeyword: "ganesh chaturthi at home", cross: ["ganesha-stories", "festival-prasadam", "hindu-kids-usa"], b1: ["festival-rituals-for-kids", "explaining-hindu-festivals-to-coworkers"], posts: [
    ["krishna-janmashtami-at-home", "Krishna Janmashtami at Home: A Midnight for Beginners", A, N, "seasonal", "krishna janmashtami at home", [], "Krishna", ""],
    ["ganesh-chaturthi-in-the-usa", "Ganesh Chaturthi in the USA: Clay, Community, Care", M, N, "seasonal", "ganesh chaturthi in usa", ["maha-ganapathy-homam", "brahmavidyaganapati"], "", ""],
    ["eco-friendly-ganesh-visarjan", "Eco-Friendly Ganesh Visarjan at Home, in a Bucket", A, N, "how-to", "eco friendly ganesh visarjan", ["brahmavidyaganapati"], "", ""],
    ["onam-mahabali-meaning", "Onam and Mahabali: The King Who Comes Home", H, G, "seasonal", "onam significance", [], "Vishnu", ""],
    ["raksha-bandhan-meaning", "Raksha Bandhan Meaning: The Thread That Protects Both", M, N, "seasonal", "raksha bandhan meaning", [KAVACH], "", ""],
  ]},
  { id: "festivals-winter-guru", name: "Guru Purnima, Kartik and winter festivals", series: "festivals", audience: G, seasonality: "Jul (Guru Purnima), Nov (Kartik), Dec–Feb (Arudra, Ratha Saptami, Vasant Panchami)", primaryKeyword: "guru purnima meaning", cross: ["festivals-aadi-monsoon", "navagraha-grahas", "mantras-explained"], b1: ["margazhi-month-meaning", "karthigai-deepam-significance"], posts: [
    ["guru-purnima-meaning", "Guru Purnima Meaning: Thanking the People Who Taught You", A, S, "seasonal", "guru purnima meaning", ["guru-jupiter-transit"], "", ""],
    ["kartik-purnima-significance", "Kartik Purnima Significance: Lamps on the Water", H, G, "seasonal", "kartik purnima significance", [], "Shiva", ""],
    ["ratha-saptami-significance", "Ratha Saptami: The Sun Turns His Chariot North", A, G, "seasonal", "ratha saptami significance", ["navagraha-homam"], "", ""],
    ["vasant-panchami-saraswati", "Vasant Panchami: Saraswati, Yellow and Spring", H, G, "seasonal", "vasant panchami significance", ["saraswati-homam"], "", ""],
    ["arudra-darshan-meaning", "Arudra Darshan: The Night Nataraja Dances", H, G, "seasonal", "arudra darshan", ["maha-shivaratri"], "", ""],
    ["tulsi-vivah-meaning", "Tulsi Vivah Meaning: The Wedding of a Plant", M, N, "seasonal", "tulsi vivah", [], "Vishnu", ""],
  ]},
  // ---------------- NRI / US ----------------
  { id: "hindu-kids-usa", name: "Raising Hindu kids in America", series: null, audience: N, seasonality: "year-round; peaks at school start and festivals", primaryKeyword: "raising hindu kids in america", cross: ["temples-in-usa", "interfaith-families", "festivals-krishna-ganesha"], b1: ["explaining-diwali-to-kids", "simple-mantras-for-kids", "festival-rituals-for-kids"], posts: [
    ["raising-hindu-kids-in-america", "Raising Hindu Kids in America Without Pressure", M, N, "how-to", "raising hindu kids in america", [], "Ganesha", ""],
    ["hindu-bedtime-stories-for-kids", "Hindu Stories for Kids at Bedtime: Where to Start", H, N, "how-to", "hindu stories for kids", [], "Ganesha", ""],
    ["bala-vihar-temple-sunday-school", "Bala Vihar: Is Temple Sunday School Worth It?", M, N, "comparison", "bala vihar", [], "Saraswati", ""],
    ["teens-questioning-hinduism", "When Your Teen Questions Hinduism: Good News, Actually", H, N, "informational", "teenager questioning religion hindu", [], "Krishna", ""],
    ["grandparents-on-video-calls", "Grandparents, Prayers and Video Calls Across Oceans", M, N, "informational", "grandparents teaching prayers online", ["ayushya-homam"], "", ""],
    ["should-kids-fast-hindu", "Should Kids Fast? A Gentle Hindu Approach", A, N, "informational", "should children fast hindu", [], "Vishnu", ""],
    ["explaining-death-to-kids-hindu", "Explaining Death to Children: A Hindu View", H, N, "informational", "explaining death to kids hindu", ["tila-homam-at-rameswaram"], "", ""],
  ]},
  { id: "temples-in-usa", name: "Hindu temples in the USA", series: null, audience: N, seasonality: "year-round; festival peaks", primaryKeyword: "hindu temple etiquette", cross: ["hindu-kids-usa", "symbols-explained", "our-temples"], b1: ["explaining-hindu-festivals-to-coworkers", "navagraha-temple-worship-guide"], posts: [
    ["first-visit-hindu-temple-usa", "Your First Visit to a Hindu Temple in the US", M, N, "how-to", "first time visiting hindu temple", [], "Ganesha", ""],
    ["what-to-wear-hindu-temple", "What to Wear to a Hindu Temple, Honestly", A, N, "how-to", "what to wear to a hindu temple", [], "Ganesha", ""],
    ["bringing-a-friend-to-temple", "Bringing a Non-Hindu Friend to the Temple", M, N, "how-to", "can non hindus visit hindu temples", [], "Ganesha", ""],
    ["volunteering-at-a-hindu-temple", "Volunteering at a Hindu Temple: Seva in the Suburbs", M, N, "informational", "volunteering at hindu temple", [ANNA], "", ""],
    ["why-us-temples-have-many-deities", "Why US Hindu Temples House Many Gods Under One Roof", H, N, "informational", "why american hindu temples have many deities", [], "Navagraha", ""],
    ["temple-festivals-in-america", "Brahmotsavam in the Suburbs: Temple Festivals in America", M, N, "seasonal", "brahmotsavam", [], "Venkateswara", ""],
  ]},
  { id: "interfaith-families", name: "Interfaith and mixed families", series: null, audience: N, seasonality: "year-round; December holidays, wedding season", primaryKeyword: "interfaith marriage hindu", cross: ["hindu-kids-usa", "seeker-questions", "marriage-and-family"], b1: ["explaining-a-hindu-wedding", "explaining-hindu-festivals-to-coworkers"], posts: [
    ["interfaith-marriage-hindu", "Interfaith Marriage and Hindu Family: Making Room", M, N, "informational", "interfaith marriage hindu", [], "Ganesha", ""],
    ["christmas-and-diwali-at-home", "Christmas and Diwali in One Home: A December Story", M, N, "informational", "celebrating diwali and christmas", ["diwali-puja"], "", ""],
    ["puja-with-a-non-hindu-spouse", "Doing Puja With a Non-Hindu Spouse", A, N, "how-to", "puja with non hindu spouse", [], "Ganesha", ""],
    ["hindu-view-of-other-religions", "What Hinduism Says About Other Religions", H, S, "informational", "hindu view of other religions", [], "Ganesha", ""],
    ["raising-interfaith-kids-hindu", "Raising Interfaith Kids With a Hindu Thread", M, N, "how-to", "raising interfaith children", [], "Krishna", ""],
  ]},
  { id: "parents-elders", name: "Parents, elders and milestone birthdays", series: null, audience: N, seasonality: "year-round; milestone birthdays", primaryKeyword: "shashtiabdapoorthi", cross: ["samskaras-abroad", "health-prayer", "end-of-life-abroad"], b1: ["booking-a-puja-for-parents", "praying-for-a-sick-parent", "ayushya-homam-star-birthday"], posts: [
    ["shashtiabdapoorthi-60th-birthday", "Shashtiabdapoorthi: Planning a Parent's 60th From Abroad", M, N, "how-to", "shashtiabdapoorthi", ["ayushya-homam", "mrityunjaya-homam"], "", ""],
    ["bheemaratha-shanti-70th-birthday", "Bheemaratha Shanti: The 70th Birthday Ritual", H, N, "informational", "bheemaratha shanti", ["ayushya-homam"], "", ""],
    ["sathabhishekam-80th-birthday", "Sathabhishekam: A Thousand Full Moons at Eighty", H, N, "informational", "sathabhishekam", ["ayushya-homam", "mrityunjaya-homam"], "", ""],
    ["parents-visiting-from-india", "When Parents Visit From India: Their Prayers in Your Home", M, N, "how-to", "parents visiting usa from india", [], "Ganesha", ""],
    ["caring-for-parents-from-abroad", "Caring for Ageing Parents From Abroad: A Steady Practice", M, N, "informational", "caring for aging parents in india from abroad", ["astrology-health"], "", ""],
    ["recording-elders-chants", "Recording Your Elders' Chants Before You Need Them", A, N, "how-to", "learning slokas from grandparents", [], "Vishnu", ""],
  ]},
  { id: "samskaras-abroad", name: "Samskaras abroad (life-cycle rites)", series: null, audience: N, seasonality: "year-round", primaryKeyword: "hindu samskaras", cross: ["parents-elders", "hindu-kids-usa", "nri-practice"], b1: ["namakaranam-in-america", "vidyarambham-first-letters", "seemantham-and-valaikappu"], posts: [
    ["sixteen-samskaras-explained", "The 16 Samskaras: Hindu Rites From Birth to Death", H, G, "informational", "16 samskaras", [], "Ganesha", ""],
    ["annaprashan-first-rice", "Annaprashan: Your Baby's First Rice, Abroad", A, N, "how-to", "annaprashan ceremony", ["ayushya-homam"], "", ""],
    ["upanayanam-in-the-usa", "Upanayanam in the USA: The Thread and What It Asks", H, N, "informational", "upanayanam in usa", ["saraswati-homam"], "", ""],
    ["mundan-first-haircut", "Mundan: The First Haircut, Temple or Home", M, N, "how-to", "mundan ceremony", ["palani"], "", ""],
    ["karnavedha-ear-piercing", "Karnavedha: The Ear-Piercing Ceremony Explained", A, N, "informational", "karnavedha ceremony", [], "Ganesha", ""],
    ["babys-first-temple-visit", "A Baby's First Temple Visit: What Families Do", M, N, "how-to", "baby first temple visit", ["garbharakshambika-oil"], "", ""],
  ]},
  { id: "end-of-life-abroad", name: "Death, grief and rites abroad", series: null, audience: N, seasonality: "year-round", primaryKeyword: "hindu funeral in usa", cross: ["parents-elders", "philosophy-basics", "health-prayer"], b1: ["when-a-parent-dies-abroad", "tarpanam-at-home", "pitru-dosha-explained"], posts: [
    ["hindu-funeral-in-the-usa", "A Hindu Funeral in the USA: What Families Do", M, N, "how-to", "hindu funeral in usa", ["tila-homam-at-rameswaram"], "", ""],
    ["immersing-ashes-from-abroad", "Immersing Ashes in India When You Live Abroad", M, N, "how-to", "immersing ashes in india from usa", ["tila-homam-at-rameswaram"], "", ""],
    ["annual-shraddham-meaning", "Annual Shraddham: Remembering on the Lunar Day", H, G, "informational", "annual shraddham", ["tila-homam-at-rameswaram"], "", ""],
    ["thirteenth-day-ceremony-meaning", "The Thirteenth Day After Death: Why Mourning Ends", H, G, "informational", "13th day ceremony after death hindu", [], "Tila Homam", ""],
    ["grief-in-hinduism", "Grief in Hinduism: Room to Mourn, Room to Heal", A, S, "informational", "hindu view of grief", ["mrityunjaya-homam"], "", ""],
  ]},
  { id: "nri-practice", name: "Practice far from home", series: null, audience: N, seasonality: "year-round; peaks before festivals", primaryKeyword: "hindu practice abroad", cross: ["temples-in-usa", "astrology-practice", "samskaras-abroad"], b1: ["hindu-festival-calendar-usa", "online-puja-from-usa-explained", "puja-items-list-for-home"], posts: [
    ["hindu-student-in-a-dorm", "A Hindu Student in a Dorm Room: Faith at College", M, N, "how-to", "hindu college student practice", [], "Saraswati", ""],
    ["how-to-read-a-panchangam", "How to Read a Panchangam: Five Limbs of the Day", H, G, "how-to", "how to read panchangam", ["ask-our-astrologer"], "", ""],
    ["festivals-alone-abroad", "Celebrating Festivals Alone Abroad: A Kinder Way", M, N, "informational", "celebrating festivals alone abroad", [], "Lakshmi", ""],
    ["finding-a-hindu-priest-usa", "Finding a Hindu Priest in the USA: What to Ask", M, N, "how-to", "finding a hindu priest in usa", ["maha-ganapathy-homam"], "", ""],
    ["flying-with-puja-items", "Flying With Puja Items: Ghee, Coconut, Kumkum", M, N, "how-to", "carrying puja items on flight", [], "prasadham", ""],
    ["school-day-off-for-diwali", "Asking School for a Day Off for a Hindu Festival", M, N, "how-to", "school holiday for diwali", [], "Diwali", ""],
    ["birth-star-for-us-born-baby", "Your US-Born Baby's Birth Star: Time Zones Explained", H, N, "informational", "nakshatra for baby born in usa", ["ask-our-astrologer"], "", ""],
  ]},
  // ---------------- SEEKER ----------------
  { id: "philosophy-basics", name: "Hindu philosophy basics", series: null, audience: S, seasonality: "year-round", primaryKeyword: "hindu philosophy basics", cross: ["gita-for-life", "many-paths", "seeker-questions"], b1: ["karma-explained-simply", "dharma-meaning-in-everyday-life", "astrology-and-free-will"], posts: [
    ["what-is-moksha", "What Is Moksha? Freedom, Not an Exit", H, S, "informational", "what is moksha", [], "Shiva", ""],
    ["atman-and-brahman", "Atman and Brahman: Who Is Asking 'Who Am I?'", A, S, "informational", "atman and brahman", [], "Shiva", ""],
    ["maya-meaning-illusion", "Maya Meaning: Not Illusion, Exactly", H, S, "informational", "maya meaning in hinduism", [], "Vishnu", ""],
    ["reincarnation-in-hinduism", "Reincarnation in Hinduism: What the Texts Actually Say", H, S, "informational", "reincarnation in hinduism", [], "Tila Homam", ""],
    ["four-purusharthas", "The Four Purusharthas: Wealth and Pleasure Are Allowed", M, S, "informational", "four purusharthas", ["career-astrology"], "", ""],
    ["three-gunas-explained", "Three Gunas Explained: Sattva, Rajas, Tamas in Your Day", A, S, "informational", "three gunas", [], "Navagraha", ""],
    ["advaita-simply-explained", "Advaita Explained Simply, With a Pot and Some Space", H, S, "informational", "advaita vedanta explained simply", [], "Shiva", ""],
    ["ahimsa-in-daily-life", "Ahimsa in Daily Life: Harm Less, Starting Small", M, S, "informational", "ahimsa meaning", [], "Annadhanam", ""],
  ]},
  { id: "gita-for-life", name: "The Bhagavad Gita for daily life", series: null, audience: S, seasonality: "year-round; Gita Jayanti in Margashirsha", primaryKeyword: "bhagavad gita for beginners", cross: ["philosophy-basics", "career-and-work", "inner-practice"], b1: ["karma-explained-simply", "dharma-meaning-in-everyday-life", "rituals-for-anxious-days"], posts: [
    ["bhagavad-gita-for-beginners", "Bhagavad Gita for Beginners: Where to Actually Start", M, S, "how-to", "bhagavad gita for beginners", [], "Krishna", ""],
    ["gita-on-work-without-attachment", "Nishkama Karma: The Gita on Work Without Clinging", A, S, "informational", "nishkama karma", ["career-astrology"], "", ""],
    ["bhagavad-gita-on-anxiety", "Bhagavad Gita on Anxiety: What Krishna Told Arjuna", A, S, "informational", "bhagavad gita on anxiety", [], "Krishna", ""],
    ["arjuna-vishada-yoga-meaning", "Arjuna's Despair: Why the Gita Begins With a Breakdown", H, S, "story", "arjuna vishada yoga", [], "Krishna", ""],
    ["sthitaprajna-steady-mind", "Sthitaprajna: The Gita's Picture of a Steady Mind", A, S, "informational", "sthitaprajna meaning", [], "Krishna", ""],
    ["gita-chapter-twelve-bhakti", "Gita Chapter 12: The Short Chapter on Devotion", M, S, "informational", "bhagavad gita chapter 12", [], "Krishna", ""],
  ]},
  { id: "inner-practice", name: "Inner practice: breath, beads and silence", series: null, audience: S, seasonality: "year-round", primaryKeyword: "hindu spiritual practice at home", cross: ["mantras-explained", "food-and-body", "gita-for-life"], b1: ["chanting-for-beginners", "meditation-vs-puja", "brahma-muhurta-waking-early"], posts: [
    ["how-to-use-a-japa-mala", "How to Use a Japa Mala: 108 Beads, One Breath", A, S, "how-to", "how to use a japa mala", [], "homam", ""],
    ["pranayama-before-pooja", "Pranayama Before Pooja: Three Breaths That Settle", A, S, "how-to", "pranayama before puja", [], "homam", ""],
    ["mouna-vratam-silence", "Mouna Vratam: A Day of Silence, Tried Honestly", A, S, "how-to", "mouna vratam", [], "Shiva", ""],
    ["why-108-is-sacred", "Why 108 Is Sacred: The Number Behind the Beads", A, S, "informational", "why 108 is sacred", [], "Durga", ""],
    ["trataka-lamp-gazing", "Trataka: Lamp Gazing as a Practice of Attention", A, S, "how-to", "trataka meditation", [], "Lakshmi", ""],
    ["likhita-japa-writing-mantras", "Likhita Japa: Writing a Mantra in a Notebook", M, S, "how-to", "likhita japa", [], "Rama", ""],
    ["surya-namaskar-meaning", "Surya Namaskar Meaning: A Greeting, Not a Workout", A, S, "informational", "surya namaskar meaning", ["navagraha-homam"], "", ""],
    ["sitting-on-the-floor-to-pray", "Why We Sit on the Floor to Pray (and Chairs Are Fine)", A, S, "informational", "why sit on floor for puja", [], "Ganesha", ""],
  ]},
  { id: "food-and-body", name: "Food, body and the offering", series: null, audience: S, seasonality: "year-round", primaryKeyword: "sattvic food", cross: ["naivedyam-recipes", "inner-practice", "weekday-vratams"], b1: ["prasad-and-gratitude", "fasting-and-focus", "ekadashi-fasting-rules"], posts: [
    ["sattvic-diet-explained", "Sattvic Diet Explained: Food That Leaves You Clear", A, S, "informational", "sattvic diet", [], "prasadham", ""],
    ["why-no-onion-garlic", "Why No Onion or Garlic in Hindu Pooja Food?", A, S, "informational", "why no onion garlic hindu", [], "prasadham", ""],
    ["eating-on-a-banana-leaf", "Eating on a Banana Leaf: Tradition and Attention", A, N, "informational", "eating on banana leaf", [], "Annadhanam", ""],
    ["eating-with-your-hands", "Eating With Your Hands: The Oldest Mindful Meal", A, S, "informational", "eating with hands benefits", [], "Annadhanam", ""],
    ["turmeric-in-hindu-ritual", "Turmeric in Hindu Ritual: Gold at the Threshold", A, G, "informational", "turmeric in hindu rituals", [], "Lakshmi", ""],
    ["cooking-as-an-offering", "Cooking as an Offering: The Kitchen as Shrine", A, S, "how-to", "cooking as offering", [ANNA], "", ""],
    ["brahmarpanam-prayer-before-meals", "Brahmarpanam: A Prayer Before Meals, Explained", M, N, "informational", "brahmarpanam prayer before food", [], "Annadhanam", ""],
  ]},
  { id: "symbols-explained", name: "Everyday symbols explained", series: null, audience: S, seasonality: "year-round", primaryKeyword: "hindu symbols meaning", cross: ["temples-in-usa", "seeker-questions", "home-rituals"], b1: ["why-do-hindus-light-lamps", "kolam-and-rangoli-meaning", "drishti-evil-eye-meaning"], posts: [
    ["vibhuti-kumkum-tilak-meaning", "Vibhuti, Kumkum, Tilak: What the Forehead Marks Mean", H, S, "informational", "why hindus apply tilak", [], "Shirdi", ""],
    ["why-ring-a-temple-bell", "Why Ring a Bell at the Temple? Sound as a Doorway", A, S, "informational", "why ring bell in temple", [], "Ganesha", ""],
    ["pradakshina-meaning", "Pradakshina Meaning: Why We Walk Around the Shrine", A, G, "informational", "pradakshina meaning", ["navagraha-homam"], "", ""],
    ["rudraksha-meaning", "Rudraksha Meaning: Shiva's Tears and How to Wear One", A, S, "informational", "rudraksha meaning", ["maha-shivaratri"], "", ""],
    ["namaste-meaning-at-work", "Namaste Meaning: More Than a Greeting at Work", M, N, "informational", "namaste meaning", [], "Ganesha", ""],
    ["why-break-a-coconut", "Why Break a Coconut at the Temple? The Ego and the Shell", H, G, "informational", "why break coconut in temple", ["temple-coconut-breaking-online"], "", ""],
    ["camphor-aarti-meaning", "Camphor Aarti Meaning: The Flame That Leaves Nothing", A, S, "informational", "why camphor in aarti", [], "Ganesha", ""],
    ["shankha-conch-meaning", "Shankha: Why the Conch Is Blown in Worship", H, S, "informational", "conch shell hinduism meaning", ["sudarsana-homam"], "", ""],
  ]},
  { id: "seeker-questions", name: "Honest questions about Hinduism", series: null, audience: S, seasonality: "year-round", primaryKeyword: "is hinduism a religion", cross: ["philosophy-basics", "many-paths", "symbols-explained"], b1: ["is-astrology-real", "spiritual-but-not-religious-hinduism", "why-do-hindus-do-rituals"], posts: [
    ["is-hinduism-a-religion", "Is Hinduism a Religion or a Way of Life?", H, S, "informational", "is hinduism a religion or way of life", [], "Ganesha", ""],
    ["why-hindus-worship-idols", "Why Do Hindus Worship Idols? Murti, Not Statue", H, S, "informational", "why do hindus worship idols", [], "Ganesha", ""],
    ["do-hindus-believe-in-one-god", "Do Hindus Believe in One God or Many?", H, S, "informational", "do hindus believe in one god", [], "Vishnu", ""],
    ["is-hinduism-vegetarian", "Do All Hindus Have to Be Vegetarian?", A, S, "informational", "are all hindus vegetarian", [], "prasadham", ""],
    ["does-prayer-work-hindu-view", "Does Prayer Work? A Hindu Answer Without Promises", M, S, "informational", "does prayer work", [], "homam", ""],
    ["are-rituals-superstition", "Are Hindu Rituals Superstition? A Fair Look", A, S, "comparison", "are hindu rituals superstition", [], "homam", ""],
    ["hindu-without-believing-in-god", "Can You Be Hindu Without Believing in God?", H, S, "informational", "can you be hindu without believing in god", [], "Shiva", ""],
    ["converting-to-hinduism", "Can You Convert to Hinduism? What Traditions Say", M, S, "informational", "can you convert to hinduism", [], "Ganesha", ""],
  ]},
  // ---------------- GENERAL PRACTICE ----------------
  { id: "astrology-practice", name: "Jyotish basics: stars, charts, timing", series: null, audience: G, seasonality: "year-round", primaryKeyword: "how to find my nakshatra", cross: ["birth-stars", "rasis", "navagraha-grahas"], b1: ["reading-your-birth-chart-calmly", "vedic-vs-western-astrology", "is-astrology-real"], posts: [
    ["how-to-find-your-nakshatra", "How to Find Your Nakshatra (Birth Star) Quickly", M, N, "how-to", "how to find my nakshatra", ["ask-our-astrologer"], "", ""],
    ["rasi-vs-nakshatra", "Rasi vs Nakshatra: Moon Sign and Birth Star Compared", H, G, "comparison", "rasi vs nakshatra", ["ask-our-astrologer"], "", ""],
    ["lagna-rising-sign-explained", "Lagna Explained: The Rising Sign in Vedic Astrology", A, G, "informational", "lagna in astrology", ["ask-our-astrologer"], "", ""],
    ["dasha-periods-explained", "Dasha Periods Explained: Life in Planetary Chapters", H, G, "informational", "vimshottari dasha explained", ["career-astrology"], "", ""],
    ["horoscope-matching-porutham", "Horoscope Matching (Porutham): The Ten Checks, Calmly", M, G, "informational", "horoscope matching porutham", ["ask-our-astrologer"], "", ""],
    ["gochara-transits-explained", "Gochara: What Planetary Transits Mean, Without Panic", A, G, "informational", "gochara transit", [SHANI], "", ""],
    ["twelve-houses-in-astrology", "The Twelve Houses in Vedic Astrology, Plainly", H, G, "informational", "12 houses in vedic astrology", ["career-astrology"], "", ""],
  ]},
  { id: "navagraha-grahas", name: "The nine planets, one by one", series: null, audience: G, seasonality: "year-round; weekday of each graha", primaryKeyword: "navagraha worship", cross: ["rasis", "astrology-practice", "weekday-vratams"], b1: ["navagraha-temple-worship-guide", "rahu-ketu-dosha-explained", "shani-sade-sati-explained"], posts: [
    ["surya-graha-worship", "Surya Graha Worship: Sunday, Sunlight and Self-Respect", A, G, "how-to", "surya graha remedies", ["navagraha-homam"], "", ""],
    ["chandra-graha-worship", "Chandra Graha: The Moon, the Mind and Monday", A, G, "informational", "chandra graha remedies", ["navagraha-homam"], "", ""],
    ["angaraka-mars-worship", "Angaraka (Mars) Worship: Tuesday and Vaitheeswaran", H, G, "informational", "angaraka dosha remedies", ["navagraha-homam"], "", ""],
    ["budha-graha-worship", "Budha Graha: Mercury, Speech and Clever Hands", H, G, "informational", "budha graha remedies", ["hayagreeva-homam"], "", ""],
    ["guru-graha-thursday-worship", "Guru Graha: Jupiter, Thursdays and Teachers", M, G, "informational", "guru graha remedies", ["guru-jupiter-transit"], "", ""],
    ["shukra-graha-worship", "Shukra Graha: Venus, Beauty and Friday Prayers", M, G, "informational", "shukra graha remedies", ["navagraha-homam"], "", ""],
    ["ketu-graha-worship", "Ketu Graha: The Headless Planet of Letting Go", H, G, "informational", "ketu graha remedies", [KALA], "", ""],
  ]},
  { id: "weekday-vratams", name: "Weekday and monthly vratams", series: null, audience: G, seasonality: "weekly and monthly (lunar)", primaryKeyword: "which god to worship on which day", cross: ["navagraha-grahas", "naivedyam-recipes", "food-and-body"], b1: ["ekadashi-fasting-rules", "pradosham-meaning", "sankatahara-chaturthi-fast"], posts: [
    ["which-god-on-which-day", "Which God to Worship on Which Day of the Week", H, G, "informational", "which god to worship on which day", ["navagraha-homam"], "", ""],
    ["somvar-vrat-monday-fast", "Monday Fast for Shiva (Somvar Vrat): A Gentle Guide", A, G, "how-to", "somvar vrat", ["maha-shivaratri"], "", ""],
    ["tuesday-worship-murugan-durga", "Tuesday Worship: Murugan, Durga and Hanuman", M, G, "informational", "tuesday god hindu", [KAVACH], "", ""],
    ["thursday-sai-baba-guru", "Thursday Prayers: Sai Baba, Dakshinamurthy, Guru", M, N, "informational", "thursday sai baba pooja", ["shirdi-sai-baba-udi-prasadham"], "", ""],
    ["friday-lakshmi-pooja", "Friday Lakshmi Pooja at Home in Ten Minutes", A, N, "how-to", "friday lakshmi pooja", [SHAKTI], "", ""],
    ["pournami-pooja-at-home", "Pournami Pooja at Home: The Full-Moon Evening", A, G, "how-to", "pournami pooja at home", [], "Lakshmi", ""],
    ["monthly-sashti-vratham", "Monthly Sashti Vratham: A Small Fast for Murugan", A, G, "how-to", "sashti viratham", ["palani"], "", ""],
    ["masik-shivaratri", "Masik Shivaratri: The Monthly Night for Shiva", H, G, "informational", "masik shivaratri", ["maha-shivaratri"], "", ""],
  ]},
  { id: "homams-explained-2", name: "Homams, one by one", series: null, audience: G, seasonality: "year-round; birthdays, exams, transits", primaryKeyword: "homam benefits", cross: ["our-temples", "mantras-explained", "health-prayer"], b1: ["what-is-a-homam", "homam-vs-puja", "online-puja-from-usa-explained"], posts: [
    ["navagraha-homam-meaning", "Navagraha Homam: What Happens and Who It Is For", H, G, "informational", "navagraha homam benefits", ["navagraha-homam"], "", ""],
    ["ganapathi-homam-meaning", "Ganapathi Homam: The Fire Ritual for Beginnings", M, N, "informational", "ganapathi homam benefits", ["maha-ganapathy-homam"], "", ""],
    ["saraswati-homam-for-students", "Saraswati Homam for Students: What It Can Mean", A, N, "informational", "saraswati homam", ["saraswati-homam"], "", ""],
    ["hayagreeva-homam-meaning", "Hayagreeva Homam: The Horse-Headed God of Learning", H, G, "informational", "hayagreeva homam", ["hayagreeva-homam"], "", ""],
    ["mrityunjaya-homam-meaning", "Mrityunjaya Homam: The Fire Ritual for Health", M, G, "informational", "mrityunjaya homam benefits", ["mrityunjaya-homam"], "", ""],
    ["chandi-homam-meaning", "Chandi Homam and the 700 Verses: What Takes Place", H, G, "informational", "chandi homam", [DURGA, "navratri-poojas-online"], "", ""],
    ["how-to-choose-a-homam", "How to Choose a Homam: Matching Ritual to Need", M, N, "how-to", "which homam to perform", ["ask-our-astrologer"], "", ""],
  ]},
  { id: "health-prayer", name: "Health, illness and prayer", series: null, audience: G, seasonality: "year-round", primaryKeyword: "hindu prayer for health", cross: ["homams-explained-2", "parents-elders", "end-of-life-abroad"], b1: ["praying-for-a-sick-parent", "mahamrityunjaya-mantra-meaning", "dhanvantari-and-healing"], posts: [
    ["prayer-before-surgery-hindu", "A Hindu Prayer Before Surgery, for You or Someone You Love", M, N, "how-to", "hindu prayer before surgery", ["mrityunjaya-homam", "dhanwantari-homam"], "", ""],
    ["illness-and-karma", "Is Illness Karma? A Kinder Reading of an Old Idea", H, S, "informational", "is illness karma", ["astrology-health"], "", ""],
    ["gratitude-after-recovery", "After Recovery: Simple Thanksgiving Rituals", A, G, "how-to", "thanksgiving pooja after recovery", ["temple-coconut-breaking-online"], "", ""],
    ["caregiver-spiritual-strength", "Caregiving and Faith: When You Are the One Holding On", M, N, "informational", "prayer for caregivers", [], "Dhanvantari", ""],
    ["chronic-illness-and-practice", "Living With Chronic Illness: A Practice That Bends", A, S, "informational", "spiritual practice with chronic illness", ["dhanwantari-homam"], "", ""],
    ["om-shanti-shanti-shanti-meaning", "Om Shanti Shanti Shanti: Why Peace Is Said Three Times", A, S, "informational", "om shanti shanti shanti meaning", [], "Mrityunjaya", ""],
  ]},
  { id: "career-and-work", name: "Work, career and livelihood", series: null, audience: N, seasonality: "year-round; peaks at appraisal and layoff seasons", primaryKeyword: "prayer for job", cross: ["dharma-in-business", "gita-for-life", "astrology-practice"], b1: ["ayudha-pooja-meaning", "fasting-with-a-desk-job", "astrology-and-free-will"], posts: [
    ["prayer-for-a-job-hindu", "Prayer for a Job: Hindu Practices While You Search", M, N, "how-to", "prayer for job hindu", ["career-astrology", "maha-ganapathy-homam"], "", ""],
    ["after-a-layoff-hindu-view", "After a Layoff: Steadiness, Visa Worries and Faith", M, N, "informational", "coping with layoff spiritually", ["career-astrology"], "", ""],
    ["prayer-before-an-interview", "A Prayer Before a Job Interview, in Two Minutes", A, N, "how-to", "prayer before interview", ["maha-ganapathy-homam"], "", ""],
    ["new-business-opening-pooja", "New Business Opening Pooja: Ganesha, Lakshmi, Kubera", H, N, "how-to", "new business opening pooja", ["maha-ganapathy-homam", "temple-coconut-breaking-online"], "", ""],
    ["small-altar-at-your-desk", "A Small Altar at Your Desk: Quiet Faith at Work", A, N, "how-to", "desk altar at work", [], "Ganesha", ""],
    ["work-as-worship", "Work as Worship: An Old Idea for an Open-Plan Office", M, S, "informational", "work is worship meaning", [], "Career", ""],
  ]},
  { id: "marriage-and-family", name: "Marriage and family life", series: null, audience: G, seasonality: "year-round; wedding season", primaryKeyword: "hindu marriage rituals meaning", cross: ["interfaith-families", "astrology-practice", "feminine-shakti"], b1: ["delay-in-marriage-remedies", "explaining-a-hindu-wedding", "waiting-for-the-right-match"], posts: [
    ["wedding-anniversary-pooja", "Wedding Anniversary Pooja: Marking the Years Quietly", M, N, "how-to", "wedding anniversary pooja", ["swayamvara-parvathi-homam", "temple-coconut-breaking-online"], "", ""],
    ["saptapadi-seven-steps-meaning", "Saptapadi Meaning: The Seven Steps, Vow by Vow", H, G, "informational", "saptapadi meaning", [], "Parvati", ""],
    ["when-marriage-is-hard", "When Marriage Is Hard: Prayer, Patience and Help", M, G, "informational", "prayer for marriage problems", [SHAKTI], "", ""],
    ["thali-mangalsutra-meaning", "Thali and Mangalsutra: What the Sacred Thread Means", H, G, "informational", "mangalsutra meaning", [], "Parvati", ""],
    ["praying-together-as-a-couple", "Praying Together as a Couple: Five Minutes, Two People", A, G, "how-to", "couple praying together hindu", [], "Shiva Parvati", ""],
    ["thalai-deepavali-newlyweds", "Thalai Deepavali: A Newlywed Couple's First Diwali", A, N, "seasonal", "thalai deepavali", ["diwali-puja"], "", ""],
  ]},
  { id: "home-rituals", name: "Home rituals and sacred objects", series: null, audience: G, seasonality: "year-round", primaryKeyword: "how to do aarti at home", cross: ["symbols-explained", "weekday-vratams", "naivedyam-recipes"], b1: ["puja-at-home-step-by-step", "small-puja-corner-apartment", "puja-items-list-for-home"], posts: [
    ["vahana-pooja-new-car", "Vahana Pooja: Blessing a New Car, Lemons and All", M, N, "how-to", "vahana pooja for new car", ["temple-coconut-breaking-online"], "", ""],
    ["kalasam-meaning", "Kalasam Meaning: The Pot That Holds the Universe", A, G, "informational", "kalash meaning", [], "Lakshmi", ""],
    ["how-to-do-aarti-at-home", "How to Do Aarti at Home: Flame, Circle, Song", A, G, "how-to", "how to do aarti at home", [], "Lakshmi", ""],
    ["cleaning-brass-puja-items", "Cleaning Brass Puja Items: Tamarind, Lemon, Time", A, N, "how-to", "how to clean brass pooja items", [], "Lakshmi", ""],
    ["old-idols-and-photos", "What to Do With Old Idols and Puja Photos", M, N, "how-to", "what to do with old god photos", [], "Ganesha", ""],
    ["incense-and-dhoop-meaning", "Incense and Dhoop: Why Smoke Belongs in Worship", A, S, "informational", "why incense in puja", [], "Ganesha", ""],
    ["flowers-for-pooja", "Flowers for Pooja: Which Flower for Which God", A, G, "informational", "which flower for which god", [], "Lakshmi", ""],
  ]},
  { id: "seva-and-giving", name: "Seva, dana and giving", series: null, audience: G, seasonality: "year-round; birthdays, anniversaries, festivals", primaryKeyword: "dana in hinduism", cross: ["dharma-in-business", "temples-in-usa", "tirukkural"], b1: ["annadhanam-feeding-as-worship", "karma-explained-simply", "prasad-and-gratitude"], posts: [
    ["seva-meaning", "Seva Meaning: Service That Is Not About You", A, S, "informational", "seva meaning", [ANNA], "", ""],
    ["dana-in-hinduism", "Dana in Hinduism: How the Tradition Thinks About Giving", M, G, "informational", "dana in hinduism", [ANNA], "", ""],
    ["go-puja-cow-worship-meaning", "Go Puja: Why Hindus Honour the Cow", H, G, "informational", "go puja meaning", [], "Krishna", ""],
    ["feeding-crows-and-birds", "Feeding Crows and Birds: A Daily Offering Explained", M, G, "informational", "why feed crows hindu", [], "Tila Homam", ""],
    ["giving-on-birthdays", "Giving on Your Birthday: A Hindu Custom Worth Keeping", M, N, "how-to", "birthday donation hindu", [ANNA, "ayushya-homam"], "", ""],
  ]},
];
